name: Working Directory and Shells
on: [push]

jobs:
  display-working-directory-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory and files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
      - name: Change Working Directory
        working-directory: /home/runner
        run: pwd
  display-working-directory-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display working directory and files
        run: |
          Get-Location
          dir
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
     